# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerapp', '0002_auto_20170320_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='text',
            field=models.TextField(),
        ),
    ]
