# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
