# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortnerapp', '0002_auto_20170406_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_word', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='wordlist',
            options={'ordering': ['-last_used']},
        ),
    ]
